name: seed_free_gae_py_3_10
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.12.0
  - scikit-learn=1.5.1
  - networkx=3.2.1
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - tqdm=4.66.4
  - jupyterlab=4.2.0
  - ipykernel=6.29.3
  - pip
  - pip:
      - torch-geometric==2.5.2
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-cluster==1.6.3
      - torch-spline-conv==1.2.2
